// src/data/products.js
const productsCategory = {
  male: [
    { name: "Product 1", image: "/images/m1.jpg", hoverImage: "/images/f11.jpg", images: {"#ffa500": "/images/f1.jpg","#008000": "/images/f10.jpg","#0000ff": "/images/f7.jpg","#aaa": "/images/f11.jpg"},price: 25.99,originalPrice: 30.99,rating: 4.5,},
    { name: "Product 12", sizes: [30, 32, 34, 36, 38],  lengths: [30, 32], description: 'A classic denim jacket with premium stitching.',  colors: [{ name: 'Black', hex: '#000' }],  category: "male", price: 75, originalPrice: 97, rating: "4.5", image: '/images/m1.jpg', hoverImage:'/images/f11.jpg',},
    { name: "Product 12", sizes: [30, 32, 34, 36, 38],  lengths: [30, 32], description: 'A classic denim jacket with premium stitching.',  colors: [{ name: 'Black', hex: '#000' }],  category: "male", price: 75, originalPrice: 97, rating: "4.5", image: '/images/m2.jpg', hoverImage:'/images/f11.jpg', },
    { name: "Product 12", sizes: [30, 32, 34, 36, 38],  lengths: [30, 32], description: 'A classic denim jacket with premium stitching.',  colors: [{ name: 'Black', hex: '#000' }],  category: "male", price: 75, originalPrice: 97, rating: "4.5", image: '/images/m3.jpg', hoverImage:'/images/f11.jpg', },
    { name: "Product 12", sizes: [30, 32, 34, 36, 38],  lengths: [30, 32], description: 'A classic denim jacket with premium stitching.',  colors: [{ name: 'Black', hex: '#000' }],  category: "male", price: 75, originalPrice: 97, rating: "4.5", image: '/images/m4.jpg', hoverImage:'/images/f11.jpg', },
    { name: "Product 12", sizes: [30, 32, 34, 36, 38],  lengths: [30, 32], description: 'A classic denim jacket with premium stitching.',  colors: [{ name: 'Black', hex: '#000' }],  category: "male", price: 75, originalPrice: 97, rating: "4.5", image: '/images/m5.jpg', hoverImage:'/images/f11.jpg', },
    { name: "Product 12", sizes: [30, 32, 34, 36, 38],  lengths: [30, 32], description: 'A classic denim jacket with premium stitching.',  colors: [{ name: 'Black', hex: '#000' }],  category: "male", price: 75, originalPrice: 97, rating: "4.5", image: '/images/m6.jpg', hoverImage:'/images/f11.jpg', },
    { name: "Product 12", sizes: [30, 32, 34, 36, 38],  lengths: [30, 32], description: 'A classic denim jacket with premium stitching.',  colors: [{ name: 'Black', hex: '#000' }],  category: "male", price: 75, originalPrice: 97, rating: "4.5", image: '/images/m7.jpg', hoverImage:'/images/f11.jpg', },
    { name: "Product 12", sizes: [30, 32, 34, 36, 38],  lengths: [30, 32], description: 'A classic denim jacket with premium stitching.',  colors: [{ name: 'Black', hex: '#000' }],  category: "male", price: 75, originalPrice: 97, rating: "4.5", image: '/images/m8.jpg', hoverImage:'/images/f11.jpg', },
    { name: "Product 12", sizes: [30, 32, 34, 36, 38],  lengths: [30, 32], description: 'A classic denim jacket with premium stitching.',  colors: [{ name: 'Black', hex: '#000' }],  category: "male", price: 75, originalPrice: 97, rating: "4.5", image: '/images/m9.jpg', hoverImage:'/images/f11.jpg', },
  ],
  female: [
    { name: "Product 12", sizes: [30, 32, 34, 36, 38],  lengths: [30, 32], description: 'A classic denim jacket with premium stitching.',  colors: [{ name: 'Black', hex: '#000' }],  category: "female", price: 75, originalPrice: 97, rating: "4.5", image: '/images/f1.jpg', hoverImage:'/images/f11.jpg', },
    { name: "Product 12", sizes: [30, 32, 34, 36, 38],  lengths: [30, 32], description: 'A classic denim jacket with premium stitching.',  colors: [{ name: 'Black', hex: '#000' }],  category: "female", price: 75, originalPrice: 97, rating: "4.5", image: '/images/f2.jpg', hoverImage:'/images/f11.jpg', },
    { name: "Product 12", sizes: [30, 32, 34, 36, 38],  lengths: [30, 32], description: 'A classic denim jacket with premium stitching.',  colors: [{ name: 'Black', hex: '#000' }],  category: "female", price: 75, originalPrice: 97, rating: "4.5", image: '/images/f3.jpg', hoverImage:'/images/f11.jpg', },
    { name: "Product 12", sizes: [30, 32, 34, 36, 38],  lengths: [30, 32], description: 'A classic denim jacket with premium stitching.',  colors: [{ name: 'Black', hex: '#000' }],  category: "female", price: 75, originalPrice: 97, rating: "4.5", image: '/images/f4.jpg', hoverImage:'/images/f11.jpg', },
    { name: "Product 12", sizes: [30, 32, 34, 36, 38],  lengths: [30, 32], description: 'A classic denim jacket with premium stitching.',  colors: [{ name: 'Black', hex: '#000' }],  category: "female", price: 75, originalPrice: 97, rating: "4.5", image: '/images/f5.jpg', hoverImage:'/images/f11.jpg', },
    { name: "Product 12", sizes: [30, 32, 34, 36, 38],  lengths: [30, 32], description: 'A classic denim jacket with premium stitching.',  colors: [{ name: 'Black', hex: '#000' }],  category: "female", price: 75, originalPrice: 97, rating: "4.5", image: '/images/f6.jpg', hoverImage:'/images/f11.jpg', },
    { name: "Product 12", sizes: [30, 32, 34, 36, 38],  lengths: [30, 32], description: 'A classic denim jacket with premium stitching.',  colors: [{ name: 'Black', hex: '#000' }],  category: "female", price: 75, originalPrice: 97, rating: "4.5", image: '/images/f7.jpg', hoverImage:'/images/f11.jpg', },
    { name: "Product 12", sizes: [30, 32, 34, 36, 38],  lengths: [30, 32], description: 'A classic denim jacket with premium stitching.',  colors: [{ name: 'Black', hex: '#000' }],  category: "female", price: 75, originalPrice: 97, rating: "4.5", image: '/images/f8.jpg', hoverImage:'/images/f11.jpg', },
    { name: "Product 12", sizes: [30, 32, 34, 36, 38],  lengths: [30, 32], description: 'A classic denim jacket with premium stitching.',  colors: [{ name: 'Black', hex: '#000' }],  category: "female", price: 75, originalPrice: 97, rating: "4.5", image: '/images/f9.jpg', hoverImage:'/images/f11.jpg', },
  ],
  kids: [
    { name: "Product 12", sizes: [30, 32, 34, 36, 38],  lengths: [30, 32], description: 'A classic denim jacket with premium stitching.',  colors: [{ name: 'Black', hex: '#000' }],  category: "kids", price: 75, originalPrice: 97, rating: "4.5", image: '/images/k1.jpg', hoverImage:'/images/f11.jpg', },
    { name: "Product 12", sizes: [30, 32, 34, 36, 38],  lengths: [30, 32], description: 'A classic denim jacket with premium stitching.',  colors: [{ name: 'Black', hex: '#000' }],  category: "kids", price: 75, originalPrice: 97, rating: "4.5", image: '/images/k2.jpg', hoverImage:'/images/f11.jpg', },
    { name: "Product 12", sizes: [30, 32, 34, 36, 38],  lengths: [30, 32], description: 'A classic denim jacket with premium stitching.',  colors: [{ name: 'Black', hex: '#000' }],  category: "kids", price: 75, originalPrice: 97, rating: "4.5", image: '/images/k3.jpg', hoverImage:'/images/f11.jpg', },
    { name: "Product 12", sizes: [30, 32, 34, 36, 38],  lengths: [30, 32], description: 'A classic denim jacket with premium stitching.',  colors: [{ name: 'Black', hex: '#000' }],  category: "kids", price: 75, originalPrice: 97, rating: "4.5", image: '/images/k4.jpg', hoverImage:'/images/f11.jpg', },
    { name: "Product 12", sizes: [30, 32, 34, 36, 38],  lengths: [30, 32], description: 'A classic denim jacket with premium stitching.',  colors: [{ name: 'Black', hex: '#000' }],  category: "kids", price: 75, originalPrice: 97, rating: "4.5", image: '/images/k5.jpg', hoverImage:'/images/f11.jpg', },
    { name: "Product 12", sizes: [30, 32, 34, 36, 38],  lengths: [30, 32], description: 'A classic denim jacket with premium stitching.',  colors: [{ name: 'Black', hex: '#000' }],  category: "kids", price: 75, originalPrice: 97, rating: "4.5", image: '/images/k6.jpg', hoverImage:'/images/f11.jpg', },
    { name: "Product 12", sizes: [30, 32, 34, 36, 38],  lengths: [30, 32], description: 'A classic denim jacket with premium stitching.',  colors: [{ name: 'Black', hex: '#000' }],  category: "kids", price: 75, originalPrice: 97, rating: "4.5", image: '/images/k7.jpg', hoverImage:'/images/f11.jpg', },
    { name: "Product 12", sizes: [30, 32, 34, 36, 38],  lengths: [30, 32], description: 'A classic denim jacket with premium stitching.',  colors: [{ name: 'Black', hex: '#000' }],  category: "kids", price: 75, originalPrice: 97, rating: "4.5", image: '/images/k8.jpg', hoverImage:'/images/f11.jpg', },
    { name: "Product 12", sizes: [30, 32, 34, 36, 38],  lengths: [30, 32], description: 'A classic denim jacket with premium stitching.',  colors: [{ name: 'Black', hex: '#000' }],  category: "kids", price: 75, originalPrice: 97, rating: "4.5", image: '/images/k9.jpg', hoverImage:'/images/f11.jpg', },
  ],
  accesories:[
    { name: "Product 12", sizes: [30, 32, 34, 36, 38],  lengths: [30, 32], description: 'A classic denim jacket with premium stitching.',  colors: [{ name: 'Black', hex: '#000' }],  category: "accesories", price: 75, originalPrice: 97, rating: "4.5", image: '/images/a1.jpg', hoverImage:'/images/f11.jpg', },
    { name: "Product 12", sizes: [30, 32, 34, 36, 38],  lengths: [30, 32], description: 'A classic denim jacket with premium stitching.',  colors: [{ name: 'Black', hex: '#000' }],  category: "accesories", price: 75, originalPrice: 97, rating: "4.5", image: '/images/a2.jpg', hoverImage:'/images/f11.jpg', },
    { name: "Product 12", sizes: [30, 32, 34, 36, 38],  lengths: [30, 32], description: 'A classic denim jacket with premium stitching.',  colors: [{ name: 'Black', hex: '#000' }],  category: "accesories", price: 75, originalPrice: 97, rating: "4.5", image: '/images/a3.jpg', hoverImage:'/images/f11.jpg', },
    { name: "Product 12", sizes: [30, 32, 34, 36, 38],  lengths: [30, 32], description: 'A classic denim jacket with premium stitching.',  colors: [{ name: 'Black', hex: '#000' }],  category: "accesories", price: 75, originalPrice: 97, rating: "4.5", image: '/images/a4.jpg', hoverImage:'/images/f11.jpg', },
    { name: "Product 12", sizes: [30, 32, 34, 36, 38],  lengths: [30, 32], description: 'A classic denim jacket with premium stitching.',  colors: [{ name: 'Black', hex: '#000' }],  category: "accesories", price: 75, originalPrice: 97, rating: "4.5", image: '/images/a5.jpg', hoverImage:'/images/f11.jpg', },
    { name: "Product 12", sizes: [30, 32, 34, 36, 38],  lengths: [30, 32], description: 'A classic denim jacket with premium stitching.',  colors: [{ name: 'Black', hex: '#000' }],  category: "accesories", price: 75, originalPrice: 97, rating: "4.5", image: '/images/a6.jpg', hoverImage:'/images/f11.jpg', },
    { name: "Product 12", sizes: [30, 32, 34, 36, 38],  lengths: [30, 32], description: 'A classic denim jacket with premium stitching.',  colors: [{ name: 'Black', hex: '#000' }],  category: "accesories", price: 75, originalPrice: 97, rating: "4.5", image: '/images/a7.jpg', hoverImage:'/images/f11.jpg', },
    { name: "Product 12", sizes: [30, 32, 34, 36, 38],  lengths: [30, 32], description: 'A classic denim jacket with premium stitching.',  colors: [{ name: 'Black', hex: '#000' }],  category: "accesories", price: 75, originalPrice: 97, rating: "4.5", image: '/images/a8.jpg', hoverImage:'/images/f11.jpg', },
    { name: "Product 12", sizes: [30, 32, 34, 36, 38],  lengths: [30, 32], description: 'A classic denim jacket with premium stitching.',  colors: [{ name: 'Black', hex: '#000' }],  category: "accesories", price: 75, originalPrice: 97, rating: "4.5", image: '/images/a9.jpg', hoverImage:'/images/f11.jpg', },
  ],
  };
  
  export default productsCategory;
  